#print(f'The multiplication table of {n} is: \n n*1 = {n*1}, \n n*2 = {n*2}, \n n*3 = {n*3}', end='')
#print(f'\n n*4 = {n*4}, \n n*5 = {n*5}, \n n*6 = {n*6}', end='')
#print(f'\n n*7 = {n*7}, \n n*8 = {n*8}, \n n*9 = {n*9}, \n n*10 = {n*10}.')
n = int(input('Please, type any number to see his multiplication table: '))
print('-'*12)
print(f'{n} x 1 = {n*1} \n{n} x 2 = {n*2} \n{n} x 3 = {n*3} \n{n} x 4 = {n*4} \n{n} x 5 = {n*5}')
print(f'{n} x 6 = {n*6} \n{n} x 7 = {n*7} \n{n} x 8 = {n*8} \n{n} x 9 = {n*9} \n{n} x 10= {n*10}')
print('-'*12)
