n = input('What is your full name? ').strip()
print('Analysing your name...')
print(f'Your name in capital letter is: {n.upper()}.')
print(f'Your name in lower letter is: {n.lower()}.')
print(f'Your name has a total of {len(n) - n.count(" ")} letters.')
#ns = n.replace(' ', '')
#print(f'Your name has a total of {len(ns)} letters.')
nd = n.split()
print(f'Your first name is {nd[0]} and it has {len(nd[0])} letters.''')
