n = int(input('Please, type any number from 0 to 9999: '))
print(f'Analysing the number {n}:')
print(f'Unit: {n // 1  % 10}')
print(f'Decimal: {n // 10 % 10}')
print(f'Hundred: {n // 100 % 10}')
print(f'Thousand: {n // 1000 % 10}')
