c = str(input('Type the name of your city of birth: ')).strip()
print(c[:5].upper() == 'SANTO')
#c = c.strip()
#print(len(c.strip()))
#print(c.count('n',0,12))
#print(c.find('Santos'))
#print('Campos' in c)
#print(c.replace('New','Nova')
#print(c.upper())
#print(c.lower())
